[test] `br_inmet_bdmep`
basedosdados/pipelines pull request #286
Opened 2023-03-28 16:33 UTC by arthurfg

registrando o flow `br_inmet_bdmep`

2023-03-29 15:38 UTC, mfagundes requested changes
Eliminar os comentários do help padrão e verificar os modelos `dbt` em `https://github.com/basedosdados/queries-basedosdados`

2023-03-29 15:38 UTC, mfagundes commented on pipelines/datasets/br_inmet_bdmep/run.py
Normalmente usamos um arquivo na raiz, chamado `tests.py`, que não entra no controle de versão.

2023-03-29 15:38 UTC, mfagundes commented on pipelines/datasets/br_inmet_bdmep/utils.py
> +    clima.replace(to_replace=-9999, value=np.nan, inplace=True)
O `np_nan` transforma os valores nulos num string "nan". Verificar se não é melhor deixar vazio ( "" )

2023-03-29 15:38 UTC, mfagundes commented on pyproject.toml
> +unicode = "^2.9"
`datetime` é um `built-in` do Python, não precisa de importação. Verificarse `unicode` não é o mesmo caso.

2023-04-03 13:45 UTC, mfagundes commented on pyproject.toml
> +unicode = "^2.9"
confesso que não conheço algum comando do `poetry`. verifique e, caso não encontre, apenas elimine as linhas do `pyproject.toml` e, caso tenha gerado, do `poetry-lock.yml`

2023-04-03 14:58 UTC, tricktx commented on pipelines/datasets/br_inmet_bdmep/schedules.py
> +                "materialize after dump": True,
Coloca `'materialize_after_dump'`

2023-04-03 15:50 UTC, mfagundes commented on pipelines/datasets/br_inmet_bdmep/schedules.py
> +            labels=[
O ideal, para rodar sempre no mesmo dia do mês, seria usar (supondo sempre no último dia do mês):
```
clocks = [
    CronClock(
        cron = "11 17 28 * *"
        start_date=datetime(2021, 3, 31, 17, 11)
...
```

Isso fará com que a pipeline rode todo dia 28, já que é o único dia presente em todos os meses. Desconheço uma forma de fazer isso para o último dia do mês, independente de qual mês seja. Outra opção seria colocar no dia 1° de cada mês. Como referência, veja o site https://crontab.guru/

2023-04-03 18:14 UTC, arthurfg commented on pipelines/datasets/br_inmet_bdmep/schedules.py
> +            labels=[
nice, atualizei aqui!

2023-04-03 19:12 UTC, mfagundes approved these changes

2023-04-11 17:52 UTC, merged