[test] access datasus ftp using prefect
basedosdados/pipelines pull request #295
Opened 2023-04-10 15:36 UTC by folhesgabriel

- Register `br_ms_cnes.estabelecimentos` 
- Verify if there's any kind of problem accessing datasus ftp with prefect, to further develop br_ms_cnes estabelecimentos pipeline
- The current flow only downloads one specific dataset from datasus ftp
- There's no materialization or data upload to GCS

2023-04-11 23:17 UTC, mfagundes approved these changes

2023-04-11 23:17 UTC, mfagundes commented on pipelines/datasets/br_ms_cnes/constants.py
> +    FOO = "bar"
Se o arquivo de constantes não é usado, pode apagá-lo

2023-04-11 23:17 UTC, mfagundes commented on pipelines/datasets/br_ms_cnes/flows.py
> +    access_datasus_cnes_ftp()
É só essa função mesmo?

2023-04-11 23:17 UTC, mfagundes commented on pipelines/datasets/br_ms_cnes/tasks.py
> +    log(f"The file {files} is in the {folder}")
Se o arquivo está sendo salvo para uso posterior, ele não deve ficar em uma pasta do agente, mas ser enviado para algum bucket. Estes arquivos não persistem nos containers. Confirmem isso, por favor, @lucascr91 e @guialvesp1

2023-04-13 16:41 UTC, laura-l-amaral requested changes
Acho que não é pra ser mergeado esse pr nesse formato né? Era só um teste correto?

2023-08-01 12:13 UTC, folhesgabriel commented
closes #399

2023-08-07 14:43 UTC, laura-l-amaral commented
closes #397

2023-08-07 19:07 UTC, tricktx commented on pipelines/datasets/br_ms_cnes/schedules.py
> +                "materialize after dump": True,
Ajustar o materialize after dump com o "_", uma vez que no flow está dessa forma.

2023-08-07 19:41 UTC, laura-l-amaral commented on pipelines/utils/utils.py
> +            `{billing_project_id}.{dataset_id}.{table_id}`
isso aqui tá certo? o nome do projeto que os dados vao ser conjuntados não é pra ser sempre igual ao billing project id, acho que são coisas diferentes

2023-08-07 20:31 UTC, folhesgabriel commented on pipelines/utils/utils.py
> +            `{billing_project_id}.{dataset_id}.{table_id}`
Na maior parte vai ser igual. A ideia é usar os projetos da BD pra acessar as tabelas mas do jeito que tá tem margem pra erro. Vou setar basedosdados e basedosdados-dev como as opções.

2023-08-09 17:34 UTC, laura-l-amaral approved these changes

2023-08-10 19:02 UTC, merged