[feat] reading files with different names in `br_ibge_pnadc`
basedosdados/pipelines pull request #298
Opened 2023-04-14 16:43 UTC by arthurfg

A partir do ano de 2022 alguns releases vieram com um nome diferente do padrão encontrado no FTP, impossibilitando o download do .zip e por isso o conjunto não está atualizado. Esse PR corrige isso.

2023-04-15 01:20 UTC, mfagundes requested changes

2023-04-15 01:20 UTC, mfagundes commented on pipelines/datasets/br_ibge_pnadc/tasks.py
> +    download_page = f"https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/{year}/"
Essa lógica tem problemas no primeiro trimestre do ano. Como o parâmetro `year` é passado como o ano atual e `quarter` é o trimestre atual, no primeiro trimestre do ano (em fevereiro) ele irá receber o ano atual e o trimestre será zero.

2023-04-15 01:20 UTC, mfagundes commented on pipelines/datasets/br_ibge_pnadc/tasks.py
> +        hrefs = [k for k in response.text.split('href="')[1:] if k.__contains__("zip")]
O `if` pode ser reescrito como `if "zip" in k`

2023-04-15 14:13 UTC, crislanealves approved these changes

2023-04-20 15:57 UTC, arthurfg commented on pipelines/datasets/br_ibge_pnadc/tasks.py
> +    download_page = f"https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/{year}/"
@mfagundes pode dar uma olhada na nova lógica que implementei?

2023-05-03 01:10 UTC, mfagundes requested changes

2023-05-03 01:10 UTC, mfagundes commented on pipelines/datasets/br_ibge_pnadc/tasks.py
> +    download_page = f"https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/{year}/"
@arthurfg desculpe a demora na resposta. Não entendi o motivo da primeira comparação. O valor, ali, é um número de 1 a 12 e a alteração no trimestre só precisa ocorrer nos 3 primeiros meses do ano. Assim, acho que bastaria `datetime.now().month <= 3`. 

Por que testar se é menor ou igual a 12? Me parece incoerente.

2023-05-04 17:07 UTC, merged