Staging/br rj isp estatisticas seguranca
basedosdados/pipelines pull request #306
Opened 2023-04-28 12:51 UTC by folhesgabriel

- Registra flows do conjunto `br_rj_isp_estatisticas_seguranca` para teste

2023-06-12 23:34 UTC, lucascr91 commented on pipelines/datasets/br_rj_isp_estatisticas_seguranca/run.py
Porque esse arquivo está aqui? Ele não é apenas para teste?

2023-06-12 23:35 UTC, lucascr91 commented on pipelines/datasets/br_rj_isp_estatisticas_seguranca/tasks.py
Pode apagar os coment'rios de instrução

2023-06-12 23:36 UTC, lucascr91 commented on pipelines/datasets/br_rj_isp_estatisticas_seguranca/utils.py
> +    dict_original = {
Isso não era para estar no arquivo constants.py?

2023-06-12 23:37 UTC, lucascr91 requested changes
Ver comentários nos arquivos individuais.

2023-06-13 01:43 UTC, tricktx commented
@lucascr91 code reviews consertada. Obrigado. :)

2023-06-14 19:44 UTC, laura-l-amaral commented on pipelines/datasets/br_rj_isp_estatisticas_seguranca/constants.py
> +dict_original = {
é necessário identar os dicionarios para que fiquem dentro da classe

2023-06-15 12:57 UTC, laura-l-amaral commented
Uma dúvida sobre os dados, como que a gente sabe o que representa o id_cisp, id_aisp, id_risp mesmo?

2023-06-15 13:02 UTC, tricktx commented
@laura-l-amaral, eu encontrei a seguinte descrição com um amigo que é PM:

As Circunscrições Integradas de Segurança Pública - CISP, correspondem às áreas territoriais de atuação e responsabilidade conjunta das delegacias distritais da Secretaria de Estado de Polícia Civil (SEPOL) e das companhias integradas da Secretaria de Estado de Polícia Militar (SEPM). As CISP têm como princípio básico o conceito de que a responsabilidade pelo policiamento de uma subárea da companhia de Polícia Militar deverá coincidir com a circunscrição de uma delegacia de Polícia Civil. Nesse sentido, as CISP constituem a esfera de integração territorial, em nível operacional, das Companhias Integradas da SEPM com as Delegacias de Polícia da SEPOL. As CISP caracterizam, segundo este modelo de integração geográfica, a menor instância de apuração dos indicadores de criminalidade.

As Áreas Integradas de Segurança Pública - correspondem, geograficamente, às áreas de atuação de um batalhão da SEPM e às circunscrições das delegacias da SEPOL contidas na área de cada batalhão. As AISP foram criadas através da Resolução SSP N. 263 de 27 de julho de 1999, como parte de uma política de segurança pública que tinha por objetivo estreitar a ligação entre as Polícias Civil e Militar, bem como destas com as comunidades abrangidas pelas AISP, por meio da gestão participativa na identificação e resolução dos problemas locais de segurança pública. A atual divisão territorial do estado do Rio de Janeiro contempla um total de 39 AISP, conforme a Resolução SESEG nº 478 de 31/05/2011, que visou adequar os limites geográficos de atuação das unidades da Polícia Civil e Militar, de forma a torná-las compatíveis aos objetivos da gestão territorial da segurança pública, segundo RISP, AISP e CISP.

As Regiões Integradas de Segurança Pública (RISP) objetivam a articulação territorial regional, no nível tático, da SEPOL com a SEPM. A adequação geográfica entre as circunscrições territoriais de atuação das Polícias, no contexto das RISP, se consolida em termos práticos ao nível dos Departamentos de Polícia de Área (DPA) da SEPOL e dos Comandos de Policiamento de Área (CPA) da SEPM. Os diretores dos DPA e os comandantes dos CPA, além das atribuições internas inerentes às suas respectivas instituições, também são responsáveis pelo estabelecimento de estratégias de integração e cooperação regionais; pela instituição de um fórum permanente de análise, compartilhamento de informações e ações conjuntas; pela adequação dos recursos humanos e logísticos às necessidades regionais; pelo acompanhamento e avaliação das ações realizadas; assim como pela promoção de uma rotina de reuniões e monitoramento do cumprimento das metas operacionais e administrativas pertinentes à sua região. O estado do Rio de Janeiro está dividido em sete RISP, conforme as seguintes abrangências territoriais:

• 1ª RISP Capital (Zona Sul, Centro e parte da Norte)
• 2ª RISP Capital (Zona Oeste e parte da Norte)
• 3ª RISP Baixada Fluminense
• 4ª RISP Grande Niterói e Região dos Lagos.
• 5ª RISP Sul Fluminense
• 6ª RISP Norte Fluminense e Noroeste
• 7ª RISP Região Serrana

`Um fator que não conseguimos achar e inclusive, mandamos e-mail, mas não houve resposta, foi o dicionário de cada código, mas eu lembro que quando conversamos sobre isso e decidimos subir dessa maneira. `

2023-06-15 13:57 UTC, lucascr91 approved these changes

2023-06-15 13:57 UTC, merged