[test] br_me_comex_stat
basedosdados/pipelines pull request #312
Opened 2023-05-05 01:03 UTC by folhesgabriel

- register flows of `br_me_comex_stat` for testing purposes

2023-05-09 19:28 UTC, crislanealves approved these changes

2023-05-10 00:31 UTC, mfagundes requested changes
Como a @crislanealves já havia revisado, apenas dei atenção ao `schedule`. Ver observação no arquivo.

2023-05-10 00:31 UTC, mfagundes commented on pipelines/datasets/br_me_comex_stat/schedules.py
> +            # the next run will be tomorrow (10/05/2023) and then every 30 days only on weekdays
Pipelines mensais não devem ser rodadas com o `IntervalClock` de 30 dias. Em apenas um ano já tem uma defasagem de vários dias, pela falta de uniformidade dos tamanhos dos meses. Melhor usar o `CronClock` (ver o site [Crontab Guru](https://crontab.guru/)

2023-05-12 23:10 UTC, lucascr91 commented on pipelines/datasets/br_me_comex_stat/schedules.py
> +            # the next run will be tomorrow (10/05/2023) and then every 30 days only on weekdays
Isso já foi resolvido @folhesgabriel ?Se não, coloca em draft, por favor

2023-05-19 17:11 UTC, folhesgabriel commented
> Só confirma se os schedules de municipio_importacao e exportacao estao corretos.

Corrigi :)

2023-05-19 17:22 UTC, merged