[dados] br_ons_avaliacao_operacao
basedosdados/pipelines pull request #323
Opened 2023-05-29 16:52 UTC by folhesgabriel

- Create pipeline for br_ons_avaliacao_operacao datasets. 
- reservatorio
- geracao_usina
- geracao_termica_motivo_despacho
- energia_natural_afluente
- energia_armazenada_reservatorio

2023-05-29 16:57 UTC, lucascr91 commented on pipelines/datasets/br_ons_avaliacao_operacao/flows.py
> +# )
Porque os schedules estão desativados nessa pipeline?

2023-05-29 16:59 UTC, lucascr91 requested changes
Ver comentário sobre os schedules

2023-05-29 17:02 UTC, folhesgabriel commented on pipelines/datasets/br_ons_avaliacao_operacao/flows.py
> +# )
Eles estão prontos! Vou rodar em dev pra depois ativar e jogar pra prod.

2023-06-06 14:39 UTC, laura-l-amaral commented on pipelines/datasets/br_ons_avaliacao_operacao/flows.py
> +        dump_mode="overwrite",
aqui é overwrite mesmo?

2023-06-14 17:44 UTC, laura-l-amaral approved these changes

2023-06-14 17:44 UTC, merged