[pipelines] br_mg_belohorizonte_smfa_iptu
basedosdados/pipelines pull request #448
Opened 2023-08-31 22:18 UTC by tricktx

2023-09-05 10:58 UTC, folhesgabriel requested changes

2023-09-05 10:58 UTC, folhesgabriel commented on pipelines/datasets/br_mg_belohorizonte_smfa_iptu/flows.py
> +from pipelines.utils.tasks import update_django_metadata
Essa é a task antiga, a nova é importada de 
`from pipelines.utils.metadata.flows import update_django_metadata`

2023-09-05 10:58 UTC, folhesgabriel commented on pipelines/datasets/br_mg_belohorizonte_smfa_iptu/flows.py
> +            update_django_metadata(
Trocar para task update_django_metadata mais recente

2023-09-05 10:58 UTC, folhesgabriel commented on pipelines/datasets/br_mg_belohorizonte_smfa_iptu/schedules.py
> +                "materialization_mode": "dev",
Settar materialization_mode como prod

2023-09-05 10:58 UTC, folhesgabriel commented on pipelines/datasets/br_mg_belohorizonte_smfa_iptu/utils.py
> +    headers = {
Olha só, nunca tomei block pra fazer um parsing simples. Só pra scrapers maiores. Mas é uma boa precaução!

2023-09-05 10:58 UTC, folhesgabriel commented on pyproject.toml
> +geopandas = "0.13.2"
Precisa colocar no Poetry.lock tbm, não?

2023-09-05 12:10 UTC, tricktx commented on pyproject.toml
> +geopandas = "0.13.2"
Então, sobre o Poetry, já existe o geopandas e o shapely lá, mas com outra versão. A princípio, não deu conflito e resolveu o meu problema.

2023-09-12 18:57 UTC, laura-l-amaral commented on pipelines/datasets/br_mg_belohorizonte_smfa_iptu/schedules.py
> +            interval=timedelta(weeks=1),
1 dia

2023-09-12 19:02 UTC, laura-l-amaral commented on pipelines/datasets/br_mg_belohorizonte_smfa_iptu/flows.py
> +from pipelines.utils.metadata.flows import update_django_metadata
acho que nao é do flow que vc tem que importar o update_django_metadata

2023-09-12 19:36 UTC, gabrielle-carv commented on pipelines/datasets/br_mg_belohorizonte_smfa_iptu/flows.py
> +                update_django_metadata(
passar o parâmetros `billing_project_id="basedosdados"` e `is_bd_pro: True`

2023-09-12 19:44 UTC, gabrielle-carv commented on pipelines/datasets/br_mg_belohorizonte_smfa_iptu/flows.py
> +                    upstream_tasks=[wait_for_materialization],
talvez o update_django_metadata esteja rodando junto com o `get_max_data`, pra ter certeza que ele vai retornar a data, por segurança talvez fosse uma boa deixar o  ` upstream_tasks` em relação ao `data_max` já que esse espera a materialização... mas depende de como eles estejam rodando

2023-09-12 21:16 UTC, gabrielle-carv commented on pipelines/datasets/br_mg_belohorizonte_smfa_iptu/tasks.py
> +    if data_obj == data_bq_obj:
a igualdade ficou

2023-09-12 21:28 UTC, tricktx commented on pipelines/datasets/br_mg_belohorizonte_smfa_iptu/tasks.py
> +    if data_obj == data_bq_obj:
Eu só subi para testar novamente as mudanças em dev.

2023-09-13 20:10 UTC, gabrielle-carv approved these changes

2023-09-13 20:28 UTC, folhesgabriel approved these changes

2023-09-13 20:46 UTC, merged