[fix] download_table
basedosdados/pipelines pull request #575
Opened 2023-11-24 18:58 UTC by laura-l-amaral

2023-12-13 13:57 UTC, folhesgabriel requested changes

2023-12-13 13:57 UTC, folhesgabriel commented on pipelines/datasets/cross_update/flows.py
> +)
Linkar com schedule

2023-12-13 18:02 UTC, laura-l-amaral commented on pipelines/datasets/cross_update/flows.py
> +)
nesse caso não precisa pq esse flow não tem schedule, ele só é chamado pelo outro

2023-12-13 18:30 UTC, arthurfg commented on pipelines/datasets/cross_update/flows.py
> +        mode=materialization_mode, upstream_tasks=[materialization_mode]
você testou com o mode = prod? só uma dúvida msm

2023-12-13 18:30 UTC, arthurfg commented on pipelines/datasets/cross_update/tasks.py
> +            query += f"SELECT * FROM `basedosdados.{schema_name}.__TABLES__` UNION ALL "
aqui eu acho que poderia selecionar apenas as colunas que são usadas para aumentar a velocidade da query, as colunas `creation_time` e `type` acho que não são usadas, né?

2023-12-13 18:30 UTC, arthurfg commented on pipelines/datasets/cross_update/utils.py
> +def get_credentials_from_secret(
as funções `get_credentials_from_secret`, `get_vault_secret`, `get_vault_client` já estão em `pipelines/utils/utils.py`

2023-12-13 18:50 UTC, laura-l-amaral commented on pipelines/datasets/cross_update/flows.py
> +        mode=materialization_mode, upstream_tasks=[materialization_mode]
sim, pq só prod tinha as permissões necessárias pra fazer todo o processo rodar

2023-12-13 18:51 UTC, laura-l-amaral commented on pipelines/datasets/cross_update/tasks.py
> +            query += f"SELECT * FROM `basedosdados.{schema_name}.__TABLES__` UNION ALL "
a velocidade da query não é um problema, ela roda bem rapidinho, separei em batchs pq não pode consultar mais de 100 conjuntos por vez. Eu não uso aqui, mas acho que são informações relevantes bacana de ter na tabela de metadados

2023-12-13 18:52 UTC, laura-l-amaral commented on pipelines/datasets/cross_update/utils.py
> +def get_credentials_from_secret(
vdd! vou arrumar

2023-12-14 13:21 UTC, folhesgabriel approved these changes

2023-12-14 13:22 UTC, merged