[feat] `to_download` task
basedosdados/pipelines pull request #638
Opened 2024-01-24 14:58 UTC by arthurfg

closes #543

2024-01-25 17:56 UTC, laura-l-amaral requested changes
Ficou bem organizadinha a função! Deu pra enteder super bem o processo e parece ser bem útil. Parabéns!

Coloquei alguns comentários de renomear coisas pra manter tudo padronizadinho e 2 comentários para levantar mais erros. Coisa rápida de resolver.  

A única coisa mais chatinha que queria conversar contigo é como passar os save_paths. Pensei em tranformar em dicionário as url com os savepaths, também pensei em mandar um único savepath, mas acho que vc deve ter um bom motivo pra não ter feito com um savepath unico. Enfim, queria avaliar as opções aqui

2024-01-25 17:56 UTC, laura-l-amaral commented on pipelines/utils/to_download/constants.py
> +Constant values for the utils projects
remover esse arquivo

2024-01-25 17:56 UTC, laura-l-amaral commented on pipelines/utils/to_download/utils.py
> +        save_paths = [save_paths]
colocar essa parte na task pra não quebrar a lógica do código na linha 50 do arquivo tasks.py

2024-01-25 17:56 UTC, laura-l-amaral commented on pipelines/utils/to_download/utils.py
> +    for url, save_path in zip(urls, save_paths):
acho que ficaria mais interessante já pedir pro usuário enviar as urls e save_paths como um dicionário ao inves de transformar duas listas em dicionario aqui. Me parece que tem menos chance de dar erros, pq com as duas listas pode acontecer da pessoa mandar só um savepath, mandar número diferente de itens em cada lista ou ainda trocar as ordens sem perceber.

2024-01-25 17:56 UTC, laura-l-amaral commented on pipelines/utils/to_download/utils.py
> +async def download_unzip(
acho melhor tirar o unzip do nome da função já que ela as vezes não faz o unzip

2024-01-25 17:56 UTC, laura-l-amaral commented on pipelines/utils/to_download/utils.py
> +            return None
Ao inves de retornar None acho que pode ser útil levantar um um erro que avisa que o tipo de arquivo não pode ser utilizado nessa função

2024-01-25 17:56 UTC, laura-l-amaral commented on pipelines/utils/to_download/utils.py
> +    pasta_destino,
acho que só essa variavel ta em portugues, melhor deixar ingles pra ficar padronizadinho

2024-01-25 17:56 UTC, laura-l-amaral commented on pipelines/utils/to_download/utils.py
> +
incluir mais um except para levantar outros tipos de erros também

2024-01-25 22:18 UTC, arthurfg commented
> Ficou bem organizadinha a função! Deu pra enteder super bem o processo e parece ser bem útil. Parabéns!
> 
> Coloquei alguns comentários de renomear coisas pra manter tudo padronizadinho e 2 comentários para levantar mais erros. Coisa rápida de resolver.
> 
> A única coisa mais chatinha que queria conversar contigo é como passar os save_paths. Pensei em tranformar em dicionário as url com os savepaths, também pensei em mandar um único savepath, mas acho que vc deve ter um bom motivo pra não ter feito com um savepath unico. Enfim, queria avaliar as opções aqui

Valeu! Eu pensei no sentido de já salvar todas as requisições em partições diferentes. Ex: baixar todos os meses da pnad -> passa a lista com 12 urls -> passa a lista 12 savepaths (um p/ cada mes) -> arquivos extraídos e organizados nas pastas. Mas pode não ser tão universal assim, talvez em dict fosse melhor mesmo.  @laura-l-amaral

2024-01-26 19:24 UTC, laura-l-amaral approved these changes

2024-01-26 19:27 UTC, merged