[dados] br_camara_dados_abertos
basedosdados/pipelines pull request #639
Opened 2024-01-25 13:24 UTC by tricktx

2024-01-26 19:47 UTC, laura-l-amaral commented on pipelines/datasets/br_camara_dados_abertos/utils.py
> +    valor = constants.TABLE_LIST_CAMARA.value[table_id]
dar um nome significativo pra variavel `valor` acho que algo como `original_table_name`

2024-01-26 20:11 UTC, tricktx commented on pipelines/datasets/br_camara_dados_abertos/utils.py
> +    valor = constants.TABLE_LIST_CAMARA.value[table_id]
justo.

2024-01-29 20:59 UTC, laura-l-amaral commented on pipelines/datasets/br_camara_dados_abertos/flows.py
>          update_django_metadata.map(
Acho qeu pra ficar mais claro aqui melhor colocar essas informações que vc deixou como lista, colocar no arquivo de  constantes como um dicionário que conecta com a tabela. algo como:
```

UPDATE_DJANGO_METADATA_INFO = { 
  "proposicao_microdados": {
       "date_format": "%Y-%m-%d",
       "date_column_name": {"date": "data"},
       "coverage_type":"part_bdpro",
       "time_delta":{"months":6}
  } 

e aí a função fica 

```
update_django_metadata(
                dataset_id=dataset_id,
                table_id=table_id,
                date_column_name=constants.UPDATE_DJANGO_METADATA_INFO.value[table_id]["date_column_name"] ,
                date_format=constants.UPDATE_DJANGO_METADATA_INFO.value[table_id]["date_format"],
                coverage_type=constants.UPDATE_DJANGO_METADATA_INFO.value[table_id]["coverage_type"],
                time_delta=constants.UPDATE_DJANGO_METADATA_INFO.value[table_id]["time_delta"],
                prefect_mode=materialization_mode,
                bq_project="basedosdados",
                upstream_tasks=[wait_for_materialization],
            )
```

2024-02-05 14:13 UTC, folhesgabriel requested changes

2024-02-05 14:13 UTC, folhesgabriel commented on pipelines/datasets/br_camara_dados_abertos/constants.py
> +    HISTORICAL_DATABASE = [True, False, False, True, True]
Não acha melhor parametrizar o HISTORICAL_DATABASE  p/ facilitar a alteração da flag?

2024-02-05 14:13 UTC, folhesgabriel commented on pipelines/datasets/br_camara_dados_abertos/schedules.py
> +every_day_camara_dados_abertos_universal = Schedule(
As runs são triggadas no mesmo momento ou o map executa de forma sequencial? 
Pelo que vi as tabelas não são grandes mas vale a pena garantir.

2024-02-05 14:29 UTC, tricktx commented on pipelines/datasets/br_camara_dados_abertos/schedules.py
> +every_day_camara_dados_abertos_universal = Schedule(
Sim, amigo. São triggadas no mesmo momento. 
As tabelas são até pequenas.

2024-02-05 15:29 UTC, folhesgabriel approved these changes

2024-02-05 16:09 UTC, merged