[feat]: add option to disable elementary models on `Executa DBT model` pipeline
basedosdados/pipelines pull request #665
Opened 2024-02-20 12:26 UTC by arthurfg

closes #649

2024-02-22 21:17 UTC, laura-l-amaral requested changes
tentei rodar no prefect e não foi, ta quebrando o executa dbt model de staging

2024-03-05 19:27 UTC, laura-l-amaral commented on pipelines/utils/execute_dbt_model/tasks.py
> +        _vars = '{"disable_dbt_artifacts_autoupload": true, "disable_run_results": true, "disable_tests_results": true, "disable_dbt_invocation_autoupload": true}'
acho que tem que mudar aqui pra que o disable_elementary não apaque o que a pessoa passou em _vars né?

2024-03-05 19:27 UTC, laura-l-amaral commented on pipelines/utils/execute_dbt_model/tasks.py
> +            vars_str = f"'{_vars}'" if disable_elementary else f'"{_vars}"'
não entendi, pras duas condições a saída é a mesma?

2024-03-05 21:04 UTC, arthurfg commented on pipelines/utils/execute_dbt_model/tasks.py
> +        _vars = '{"disable_dbt_artifacts_autoupload": true, "disable_run_results": true, "disable_tests_results": true, "disable_dbt_invocation_autoupload": true}'
beleza, vou mudar. Tinha deixado assim pq nenhum modelo nossa usa variáveis passadas no cli, pelo menos acho que não

2024-03-05 21:07 UTC, arthurfg commented on pipelines/utils/execute_dbt_model/tasks.py
> +        _vars = '{"disable_dbt_artifacts_autoupload": true, "disable_run_results": true, "disable_tests_results": true, "disable_dbt_invocation_autoupload": true}'
criei essa função `merge_vars()` que junta os dois dicionários, se tiver disable_elementary = True e se tiver passado alguma `_vars`. Eles precisam estar nesse formato específico YAML, mas como string. 
```py
    if disable_elementary:
        _vars = constants.DISABLE_ELEMENTARY_VARS.value if _vars is None else merge_vars(constants.DISABLE_ELEMENTARY_VARS.value, _vars)

```

2024-03-06 19:11 UTC, laura-l-amaral commented on pipelines/utils/execute_dbt_model/utils.py
> +        print(f"Erro ao mesclar variáveis: {e}")
é melhor que o código quebre se der erro aqui

2024-03-06 19:22 UTC, laura-l-amaral commented on pipelines/utils/execute_dbt_model/tasks.py
> +        _vars = '{"disable_dbt_artifacts_autoupload": true, "disable_run_results": true, "disable_tests_results": true, "disable_dbt_invocation_autoupload": true}'
Apesar da gente não usar em flows, já usei algumas vezes esse campo quando precisei usar o full-refresh, e de qualquer forma não faz sentido a gente só substituir o valor de uma variável por outra. Poderiamos excluir a variável do flow, mas não só ignorar que ela está ali no meio 

sobre a função, tudo certinho, só coloquei um comentário ali em baixo sobre a função rodar mesmo quando da erro, melhor não deixar isso.

Não entendi o que vc disse sobre precisar estar no formato yaml, a variável _vars é um dicionario ou uma lista, o formato yaml seria uma forma específica de organizar esse dicionario ou lista?

2024-03-06 19:51 UTC, arthurfg commented on pipelines/utils/execute_dbt_model/tasks.py
> +        _vars = '{"disable_dbt_artifacts_autoupload": true, "disable_run_results": true, "disable_tests_results": true, "disable_dbt_invocation_autoupload": true}'
Aham, beleza. O Pr está pronto, agora dá pra passar _vars + disable_elementary = True.

**Sobre o que disse do formato yaml:**

<img width="819" alt="Captura de Tela 2024-03-06 às 16 50 04" src="https://github.com/basedosdados/pipelines/assets/62671380/bbcff78d-61d3-4dd2-b55f-3781d9c79adc">

2024-03-06 20:47 UTC, laura-l-amaral commented on pipelines/utils/execute_dbt_model/flows.py
> +    disable_elementary = Parameter("disable_elementary", default=False, required=False)
não é melhor o padrão ser True? pq normalmente a gente só preenche os parametros na mão quando vai testar e aí a gente não quer ativar o elementary

2024-03-07 00:04 UTC, arthurfg commented on pipelines/utils/execute_dbt_model/utils.py
> +        print(f"Erro ao mesclar variáveis: {e}")
Aham, inclui um `raise` pra parar o flow. Aqui o erro com `_vars` e `elementary` quebrando: 
<img width="1311" alt="Captura de Tela 2024-03-06 às 21 03 51" src="https://github.com/basedosdados/pipelines/assets/62671380/99e218bd-72aa-4789-98c4-1a38b676d0de">

2024-03-07 00:04 UTC, arthurfg commented on pipelines/utils/execute_dbt_model/utils.py
> +        print(f"Erro ao mesclar variáveis: {e}")
Quando puder, pode dar o approve?

2024-03-07 16:43 UTC, laura-l-amaral approved these changes

2024-03-07 19:20 UTC, merged