fix: br_mp_pep_cargos_funcoes
basedosdados/pipelines pull request #693
Opened 2024-03-04 12:42 UTC by aspeddro

2024-03-06 14:39 UTC, aspeddro commented on pipelines/datasets/br_mp_pep_cargos_funcoes/flows.py
>      dbt_alias = Parameter("dbt_alias", default=False, required=False)
Mudar para `True`

2024-03-13 17:13 UTC, laura-l-amaral approved these changes

2024-03-13 17:23 UTC, laura-l-amaral requested changes
fui rodar de novo na cloud e deu um erro igual ao do patrick com a ans, acho que o o site ta bloqueando a gente

2024-03-14 12:17 UTC, aspeddro commented
Ok, fiz algumas alterações. 

Executei o flow duas vezes hoje. Primeiro com label basedosdados-dev e agora em prod. Os dois foram executados com sucesso, o que é bem raro.

https://prefect.basedosdados.org/default/flow/ddb82c26-36bb-4ea5-99fa-c2f4bda4e104?overview&version=369


Vc acha que podemos seguir?

2024-03-14 17:11 UTC, laura-l-amaral approved these changes

2024-03-14 17:29 UTC, merged