[fix] br_anatel
basedosdados/pipelines pull request #701
Opened 2024-03-06 18:02 UTC by laura-l-amaral

2024-03-31 22:25 UTC, tricktx commented
### A partir do próximo commit, irei refatorar as duas pipelines.

2024-04-03 19:28 UTC, laura-l-amaral commented on pipelines/utils/crawler_anatel/telefonia_movel/tasks.py
> +def get_max_date_in_table_microdados(ano: int, semestre: int):
talvez colocar o decorador aqui

2024-04-05 17:06 UTC, folhesgabriel requested changes

2024-04-05 17:06 UTC, folhesgabriel commented on pipelines/utils/crawler_anatel/banda_larga_fixa/tasks.py
> +def treatment(table_id:str, ano: int):
Essas funções sem decorators são tasks?
Se forem, tá faltando o decorator. Se não, acho que vale colocar em utils e importá-las aqui se necessário

2024-04-05 17:06 UTC, folhesgabriel commented on pipelines/utils/crawler_anatel/telefonia_movel/tasks.py
> +# ! TASK MICRODADOS
mesmo comentário anterior

2024-04-08 15:46 UTC, folhesgabriel approved these changes

2024-04-08 15:46 UTC, merged