[fix] br_stf_corte_aberta.decisoes
basedosdados/pipelines pull request #853
Opened 2024-09-04 03:30 UTC by tricktx

2024-09-04 11:33 UTC, laura-l-amaral requested changes

2024-09-04 11:33 UTC, laura-l-amaral commented on Dockerfile
> +RUN apt-get update && apt-get install -y wget bzip2 libxtst6 libgtk-3-0 libx11-xcb-dev libdbus-glib-1-2 libxt6 libpci-dev && rm -rf /var/lib/apt/lists/*
@tricktx acho que é importante rever a forma como vc ta adicionando esses pacotes aqui, gostaria que garantisse com alguém que manja de docker se essa é a maneira correta de fazer isso

2024-09-04 13:41 UTC, tricktx commented on Dockerfile
> +RUN apt-get update && apt-get install -y wget bzip2 libxtst6 libgtk-3-0 libx11-xcb-dev libdbus-glib-1-2 libxt6 libpci-dev && rm -rf /var/lib/apt/lists/*
Também acho muito justo ajustar a formação. Irei verificar isso.

2024-09-04 19:12 UTC, jhony-spocket approved these changes

2024-09-05 13:03 UTC, laura-l-amaral approved these changes

2024-09-05 13:57 UTC, merged